#!/usr/bin/env python3
r"""Generate src/tokenizer/unicode_tables.inc: codepoint ranges for \p{L}, \p{N}, \s.
Run once per Python/Unicode version bump; the output is committed."""
import sys, unicodedata

def ranges(pred):
    out, start = [], None
    for cp in range(0x110000):
        ok = pred(cp)
        if ok and start is None: start = cp
        if not ok and start is not None: out.append((start, cp - 1)); start = None
    if start is not None: out.append((start, 0x10FFFF))
    return out

L = ranges(lambda c: unicodedata.category(chr(c)).startswith('L'))
N = ranges(lambda c: unicodedata.category(chr(c)).startswith('N'))
# Rust regex \s == Unicode White_Space property.
WS = set(range(0x09, 0x0E)) | {0x20, 0x85, 0xA0, 0x1680} | set(range(0x2000, 0x200B)) | {0x2028, 0x2029, 0x202F, 0x205F, 0x3000}
S = ranges(lambda c: c in WS)

with open(sys.argv[1], 'w') as f:
    f.write(f"// generated by scripts/gen_unicode_tables.py, unicode {unicodedata.unidata_version}\n")
    for name, r in (("kLetterRanges", L), ("kNumberRanges", N), ("kSpaceRanges", S)):
        f.write(f"static const uint32_t {name}[][2] = {{\n")
        for a, b in r: f.write(f"  {{0x{a:X},0x{b:X}}},\n")
        f.write("};\n")
print("letters", len(L), "numbers", len(N), "spaces", len(S))
